// Constants for Pokemon types, moves, and game mechanics
// Based on Pokemon Showdown specifications

export const POKEMON_TYPES = {
  NORMAL: 'normal',
  FIRE: 'fire',
  WATER: 'water',
  ELECTRIC: 'electric',
  GRASS: 'grass',
  ICE: 'ice',
  FIGHTING: 'fighting',
  POISON: 'poison',
  GROUND: 'ground',
  FLYING: 'flying',
  PSYCHIC: 'psychic',
  BUG: 'bug',
  ROCK: 'rock',
  GHOST: 'ghost',
  DRAGON: 'dragon',
  DARK: 'dark',
  STEEL: 'steel',
  FAIRY: 'fairy',
} as const;

export type PokemonType = typeof POKEMON_TYPES[keyof typeof POKEMON_TYPES];

export const TYPE_COLORS = {
  [POKEMON_TYPES.NORMAL]: '#A8A878',
  [POKEMON_TYPES.FIRE]: '#F08030',
  [POKEMON_TYPES.WATER]: '#6890F0',
  [POKEMON_TYPES.ELECTRIC]: '#F8D030',
  [POKEMON_TYPES.GRASS]: '#78C850',
  [POKEMON_TYPES.ICE]: '#98D8D8',
  [POKEMON_TYPES.FIGHTING]: '#C03028',
  [POKEMON_TYPES.POISON]: '#A040A0',
  [POKEMON_TYPES.GROUND]: '#E0C068',
  [POKEMON_TYPES.FLYING]: '#A890F0',
  [POKEMON_TYPES.PSYCHIC]: '#F85888',
  [POKEMON_TYPES.BUG]: '#A8B820',
  [POKEMON_TYPES.ROCK]: '#B8A038',
  [POKEMON_TYPES.GHOST]: '#705898',
  [POKEMON_TYPES.DRAGON]: '#7038F8',
  [POKEMON_TYPES.DARK]: '#705848',
  [POKEMON_TYPES.STEEL]: '#B8B8D0',
  [POKEMON_TYPES.FAIRY]: '#EE99AC',
} as const;

export const MOVE_CATEGORIES = {
  PHYSICAL: 'physical',
  SPECIAL: 'special',
  STATUS: 'status',
} as const;

export type MoveCategory = typeof MOVE_CATEGORIES[keyof typeof MOVE_CATEGORIES];

export const BATTLE_STATUSES = {
  PARALYSIS: 'paralysis',
  SLEEP: 'sleep',
  FREEZE: 'freeze',
  BURN: 'burn',
  POISON: 'poison',
  CONFUSION: 'confusion',
  FLINCH: 'flinch',
} as const;

export type BattleStatus = typeof BATTLE_STATUSES[keyof typeof BATTLE_STATUSES];

export const WEATHER_CONDITIONS = {
  NONE: 'none',
  SUNNY: 'sunny',
  RAINY: 'rainy',
  SANDSTORM: 'sandstorm',
  HAIL: 'hail',
} as const;

export type WeatherCondition = typeof WEATHER_CONDITIONS[keyof typeof WEATHER_CONDITIONS];

export const TERRAIN_TYPES = {
  NONE: 'none',
  GRASSY: 'grassy',
  MISTY: 'misty',
  ELECTRIC: 'electric',
  PSYCHIC: 'psychic',
} as const;

export type TerrainType = typeof TERRAIN_TYPES[keyof typeof TERRAIN_TYPES];

export const BATTLE_EVENTS = {
  DAMAGE: 'damage',
  MISS: 'miss',
  STATUS: 'status',
  STATUS_DAMAGE: 'status_damage',
  SWITCH: 'switch',
  FAINT: 'faint',
  WEATHER_START: 'weather_start',
  WEATHER_END: 'weather_end',
  TERRAIN_START: 'terrain_start',
  TERRAIN_END: 'terrain_end',
} as const;

export type BattleEvent = typeof BATTLE_EVENTS[keyof typeof BATTLE_EVENTS];

export const LOBBY_STATUSES = {
  OPEN: 'open',
  FULL: 'full',
  IN_PROGRESS: 'in_progress',
  FINISHED: 'finished',
  CANCELLED: 'cancelled',
} as const;

export type LobbyStatus = typeof LOBBY_STATUSES[keyof typeof LOBBY_STATUSES];

export const BATTLE_STATUSES_ENUM = {
  WAITING: 'waiting',
  IN_PROGRESS: 'in_progress',
  FINISHED: 'finished',
  CANCELLED: 'cancelled',
} as const;

export type BattleStatusType = typeof BATTLE_STATUSES_ENUM[keyof typeof BATTLE_STATUSES_ENUM];

export const RARITIES = {
  COMMON: 'common',
  RARE: 'rare',
  EPIC: 'epic',
  LEGENDARY: 'legendary',
  MYTHICAL: 'mythical',
} as const;

export type Rarity = typeof RARITIES[keyof typeof RARITIES];

// Utility functions
export const getTypeColor = (type: PokemonType): string => {
  return TYPE_COLORS[type] || '#68A090';
};

export const getRarityColor = (rarity: Rarity): string => {
  switch (rarity) {
    case RARITIES.COMMON:
      return '#9CA3AF';
    case RARITIES.RARE:
      return '#3B82F6';
    case RARITIES.EPIC:
      return '#8B5CF6';
    case RARITIES.LEGENDARY:
      return '#F59E0B';
    case RARITIES.MYTHICAL:
      return '#EF4444';
    default:
      return '#9CA3AF';
  }
};

export const getStatusColor = (status: BattleStatus): string => {
  switch (status) {
    case BATTLE_STATUSES.PARALYSIS:
      return '#F59E0B';
    case BATTLE_STATUSES.SLEEP:
      return '#8B5CF6';
    case BATTLE_STATUSES.FREEZE:
      return '#06B6D4';
    case BATTLE_STATUSES.BURN:
      return '#EF4444';
    case BATTLE_STATUSES.POISON:
      return '#A855F7';
    case BATTLE_STATUSES.CONFUSION:
      return '#EC4899';
    case BATTLE_STATUSES.FLINCH:
      return '#F97316';
    default:
      return '#6B7280';
  }
};

// Type effectiveness chart (Gen 8)
export const TYPE_EFFECTIVENESS: Record<PokemonType, Record<PokemonType, number>> = {
  [POKEMON_TYPES.NORMAL]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 0.5, [POKEMON_TYPES.GHOST]: 0, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.FIRE]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 0.5, [POKEMON_TYPES.WATER]: 0.5,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 2, [POKEMON_TYPES.ICE]: 2,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 2,
    [POKEMON_TYPES.ROCK]: 0.5, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 0.5,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 2, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.WATER]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 2, [POKEMON_TYPES.WATER]: 0.5,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 0.5, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 2,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 2, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 0.5,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 1, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.ELECTRIC]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 2,
    [POKEMON_TYPES.ELECTRIC]: 0.5, [POKEMON_TYPES.GRASS]: 0.5, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 0,
    [POKEMON_TYPES.FLYING]: 2, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 0.5,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 1, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.GRASS]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 0.5, [POKEMON_TYPES.WATER]: 2,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 0.5, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 0.5, [POKEMON_TYPES.GROUND]: 2,
    [POKEMON_TYPES.FLYING]: 0.5, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 0.5,
    [POKEMON_TYPES.ROCK]: 2, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 0.5,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.ICE]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 0.5, [POKEMON_TYPES.WATER]: 0.5,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 2, [POKEMON_TYPES.ICE]: 0.5,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 2,
    [POKEMON_TYPES.FLYING]: 2, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 2,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.FIGHTING]: {
    [POKEMON_TYPES.NORMAL]: 2, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 2,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 0.5, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 0.5, [POKEMON_TYPES.PSYCHIC]: 0.5, [POKEMON_TYPES.BUG]: 0.5,
    [POKEMON_TYPES.ROCK]: 2, [POKEMON_TYPES.GHOST]: 0, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 2, [POKEMON_TYPES.STEEL]: 2, [POKEMON_TYPES.FAIRY]: 0.5,
  },
  [POKEMON_TYPES.POISON]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 2, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 0.5, [POKEMON_TYPES.GROUND]: 0.5,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 0.5, [POKEMON_TYPES.GHOST]: 0.5, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0, [POKEMON_TYPES.FAIRY]: 2,
  },
  [POKEMON_TYPES.GROUND]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 2, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 2, [POKEMON_TYPES.GRASS]: 0.5, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 2, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 0, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 0.5,
    [POKEMON_TYPES.ROCK]: 2, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 2, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.FLYING]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 0.5, [POKEMON_TYPES.GRASS]: 2, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 2, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 2,
    [POKEMON_TYPES.ROCK]: 0.5, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.PSYCHIC]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 2, [POKEMON_TYPES.POISON]: 2, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 0.5, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 0, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.BUG]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 0.5, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 2, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 0.5, [POKEMON_TYPES.POISON]: 0.5, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 0.5, [POKEMON_TYPES.PSYCHIC]: 2, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 0.5, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 2, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 0.5,
  },
  [POKEMON_TYPES.ROCK]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 2, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 2,
    [POKEMON_TYPES.FIGHTING]: 0.5, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 0.5,
    [POKEMON_TYPES.FLYING]: 2, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 2,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.GHOST]: {
    [POKEMON_TYPES.NORMAL]: 0, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 2, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 2, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 0.5, [POKEMON_TYPES.STEEL]: 1, [POKEMON_TYPES.FAIRY]: 1,
  },
  [POKEMON_TYPES.DRAGON]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 2,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 0,
  },
  [POKEMON_TYPES.DARK]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 1, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 0.5, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 2, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 2, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 0.5, [POKEMON_TYPES.STEEL]: 1, [POKEMON_TYPES.FAIRY]: 0.5,
  },
  [POKEMON_TYPES.STEEL]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 0.5, [POKEMON_TYPES.WATER]: 0.5,
    [POKEMON_TYPES.ELECTRIC]: 0.5, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 2,
    [POKEMON_TYPES.FIGHTING]: 1, [POKEMON_TYPES.POISON]: 1, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 2, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 1,
    [POKEMON_TYPES.DARK]: 1, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 2,
  },
  [POKEMON_TYPES.FAIRY]: {
    [POKEMON_TYPES.NORMAL]: 1, [POKEMON_TYPES.FIRE]: 0.5, [POKEMON_TYPES.WATER]: 1,
    [POKEMON_TYPES.ELECTRIC]: 1, [POKEMON_TYPES.GRASS]: 1, [POKEMON_TYPES.ICE]: 1,
    [POKEMON_TYPES.FIGHTING]: 2, [POKEMON_TYPES.POISON]: 0.5, [POKEMON_TYPES.GROUND]: 1,
    [POKEMON_TYPES.FLYING]: 1, [POKEMON_TYPES.PSYCHIC]: 1, [POKEMON_TYPES.BUG]: 1,
    [POKEMON_TYPES.ROCK]: 1, [POKEMON_TYPES.GHOST]: 1, [POKEMON_TYPES.DRAGON]: 2,
    [POKEMON_TYPES.DARK]: 2, [POKEMON_TYPES.STEEL]: 0.5, [POKEMON_TYPES.FAIRY]: 1,
  },
};

export const calculateTypeEffectiveness = (attackType: PokemonType, targetTypes: PokemonType[]): number => {
  let effectiveness = 1;
  for (const targetType of targetTypes) {
    effectiveness *= TYPE_EFFECTIVENESS[attackType][targetType];
  }
  return effectiveness;
};
